import {execFileSync} from "node:child_process";
import {existsSync, readFileSync, statSync} from "node:fs";
import process from "node:process";

const errors = [];

function readJson(path) {
	try {
		return JSON.parse(readFileSync(path, "utf8"));
	} catch (error) {
		errors.push(`${path} must be valid JSON: ${error.message}`);
		return {};
	}
}

function requireFile(path) {
	if (!existsSync(path)) {
		errors.push(`${path} is required.`);
		return false;
	}
	return true;
}

function assert(condition, message) {
	if (!condition) {
		errors.push(message);
	}
}

const manifest = readJson("manifest.json");
const packageJson = readJson("package.json");
const versions = readJson("versions.json");

for (const file of ["README.md", "LICENSE", "manifest.json", "versions.json", "package.json", "package-lock.json", "tsconfig.json", "esbuild.config.mjs", "styles.css"]) {
	requireFile(file);
}

assert(/^[a-z0-9-]+$/.test(manifest.id ?? ""), "manifest.id must be lowercase kebab-case.");
assert(!(manifest.id ?? "").includes("obsidian"), "manifest.id must not contain 'obsidian'.");
assert(manifest.version === packageJson.version, "manifest.json and package.json versions must match.");
assert(versions[manifest.version] === manifest.minAppVersion, "versions.json must map the current manifest version to minAppVersion.");
assert(typeof manifest.description === "string" && manifest.description.length <= 250, "manifest.description must be 250 characters or fewer.");
assert(typeof manifest.description === "string" && manifest.description.endsWith("."), "manifest.description must end with a period.");
assert(manifest.isDesktopOnly === false, "manifest.isDesktopOnly should be false for this mobile-compatible plugin.");

const packageLock = readJson("package-lock.json");
assert(packageLock.version === packageJson.version, "package-lock.json root version must match package.json.");
assert(packageLock.packages?.[""]?.version === packageJson.version, "package-lock.json package version must match package.json.");
assert(!packageJson.dependencies || Object.keys(packageJson.dependencies).length === 0, "Runtime dependencies should be empty for bundled Obsidian plugins.");
assert(packageJson.devDependencies?.obsidian, "obsidian must be listed as a devDependency.");

const esbuildConfig = readFileSync("esbuild.config.mjs", "utf8");
assert(esbuildConfig.includes('"obsidian"'), "esbuild config must keep obsidian external.");

for (const asset of ["manifest.json", "main.js", "styles.css"]) {
	if (!requireFile(asset)) {
		continue;
	}
	assert(statSync(asset).size > 0, `${asset} must not be empty.`);
}

const mainJs = existsSync("main.js") ? readFileSync("main.js", "utf8") : "";
assert(mainJs.includes("THIS IS A GENERATED/BUNDLED FILE BY ESBUILD"), "main.js should be generated by the configured bundler.");
assert(!mainJs.includes("sourceMappingURL=data:"), "production main.js must not include an inline sourcemap.");

let trackedFiles = "";
try {
	trackedFiles = execFileSync("git", ["ls-files"], {encoding: "utf8"});
} catch {
	trackedFiles = "";
}
for (const forbidden of ["main.js", "data.json", "node_modules"]) {
	assert(!trackedFiles.split(/\r?\n/).some((file) => file === forbidden || file.startsWith(`${forbidden}/`)), `${forbidden} must not be tracked.`);
}

if (errors.length > 0) {
	console.error(errors.map((error) => `- ${error}`).join("\n"));
	process.exit(1);
}

console.log(`Release check passed for ${manifest.id} ${manifest.version}.`);
